name = "spagurders-techplus"
author = "murder_spagurder"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be60102da832188bba6470f3a83469dc48e2b6d9a1030fd1357058ff1c4f10ff"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
