name = "spagurders-techplus"
author = "murder_spagurder"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b39c39c4523afe9f08de30d287b138b9e3c0f830f21d616d340ce52836a19e60"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
