name = "spagurders-techplus"
author = "murder_spagurder"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a065568b64091c67179481a417a7c069e0dff6a372788119a2009a1fc51ef98c"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
